### ISSUE TITLE
TH1 methods `values`, `variances`, `allvalues`, `allvariances` should return numpy arrays, not lists

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot-methods#18]
These methods currently return copies of internal lists. It would be more convenient and potentially faster to return numpy arrays instead of lists. arrays are faster to allocate and expected in a context of numerical computing.

**Comment by jpivarski** [comment]
This may need to be coordinated with scikit-hep/uproot#194.

I see that PR #19 just wraps the lists as Numpy arrays. If you're content with that (ROOT file bytes → Python lists → Numpy arrays), then there's no coupling between uproot-methods version and uproot version.

If, however, you want to avoid the double conversion because the histograms are big enough to notice the performance difference (content much, much larger than axis metadata), then I'll need to change the `TArray*` implementation, which is a deep, though possible change in uproot.

Maybe just set the API to be Numpy now and the internals can change later.

**Comment by HDembinski** [comment]
Agreed, I mostly care about the API, at this point performance does not seem like an issue. The internal change could come at a later point.
