### ISSUE TITLE
Unexpected behaviour of cartesian product of TVector3Arrays

### ISSUE THREAD

**Issue by phylsix** [scikit-hep/uproot-methods#26]
Hello,

I met an error when trying to get a cartesian product of two TVector3Arrays. Below is how to reproduce the error:

```python
from awkward import JaggedArray # v0.7.0
from uproot_methods import TVector3Array # v0.3.1
import numpy as np # v1.14.2

_x = JaggedArray.fromoffsets([0,3,3,5,10], np.zeros(10))
_y = JaggedArray.fromoffsets([0,3,3,5,10], np.array([1]*10))
_z = JaggedArray.fromoffsets([0, 3,3,5,10], np.array([2]*10))
v = TVector3Array.from_cartesian(_x, _y, _z)

_xx = JaggedArray.fromoffsets([0,2,7,8,10], np.array([4]*10))
_yy = JaggedArray.fromoffsets([0,2,7,8,10], np.array([5]*10))
_zz= JaggedArray.fromoffsets([0,2,7,8,10], np.array([6]*10))
vv = TVector3Array.from_cartesian(_xx, _yy, _zz)

v.cross(vv)
# or v.cross(vv, nested=True)
```

The error seems to be related with `TVector3`'s `.cross()` method. I didn't dig deep..
Could you pls take a look? Thanks!

It's an awesome set of packages! 👍🏼

**Comment by jpivarski** [comment]
Sorry it took me a while to reproduce this. It's a name conflict— no bug to resolve, unless we decide to resolve it by changing something's name. The question is, which name?

JaggedArray has a `cross` method that means entry-by-entry [cross-join](https://en.wikipedia.org/wiki/Join_(SQL)#Cross_join). It's the one you seem to want in this case, since you made jagged arrays with different jagged structure (`v.counts != vv.counts`).

TVector3 has a `cross` method that means subentry-by-subentry [cross-product](https://en.wikipedia.org/wiki/Cross_product). This is the one that comes first in the overload order, the one that tries to run in your example. The error message is correct: you can't cross-product these jagged arrays because they have different jagged structure, just as you can't add them, take a dot product, etc. The specific error message is "cannot fit contents of JaggedArray into the given starts and stops arrays" because it tries to modify the physical structure of the arrays to fit if they have the same logical structure (see [overview](https://github.com/scikit-hep/awkward-array/blob/master/specification.adoc#jaggedness)).

You can get what you want by specifying the class explicitly:

```python
JaggedArray.cross(v, vv)    # with nested=True if you want
```

About "fixing" this problem, it would come down to renaming one of these two functions. `JaggedArray.cross` is now fairly well established: I've included it in every presentation I've made on awkward-arrays and we've been using that name quite a lot. `TVector3.cross`, while not as widely advertised, is the guessable name. Any 3-d vector class would have a `cross` method with this meaning. Renaming `JaggedArray.cross` (to what?) would mean a lot of clean-up, changing terminology that people have just gotten used to. Renaming `TVector3.cross` probably wouldn't help because users would guess that it should exist and run into exactly the problem you had above.

Maybe the only option is to include a note in the documentation, when these functions finally get documented.

**Comment by phylsix** [comment]
Thanks for detailed explanation! `JaggedArray.cross` is good enough for me ( I didn't know before). Yeah, adding a note on the documentation or docstring would be good.👍🏼
