### ISSUE TITLE
Bug in rotatex and family

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot-methods#27]
If d is a TVector3 or TVector3Array:

```python
d.rotatex(np.pi/2)
```

gives:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-a7bcb9559055> in <module>()
----> 1 d.rotatex(np.pi/2)

~/anaconda3/lib/python3.7/site-packages/uproot_methods/classes/TVector3.py in rotatex(self, angle)
     98 
     99     def rotatex(self, angle):
--> 100         return self.rotate_axis(Methods(1.0, 0.0, 0.0), angle)
    101 
    102     def rotatey(self, angle):

TypeError: Methods() takes no arguments
```

Also, there's no way to use a rotation matrix.

**Comment by jpivarski** [comment]
I did the immediate fix for `rotatex`, `rotatey`, `rotatez` by replacing `Methods` with `TVector3`. I'd like to add a function for applying a matrix in the same PR (#29). Perhaps it should be called `transform` (because it might not be a rotation)? I know what the API would look like if you want to pass in one matrix, to transform all `TVector3s` in the array by a constant, but what would the interface look like for passing in an array of matrices (with the same length as the `TVector3s`)?

Also, `TVector2` is missing an analogue of all of this. Once it's figured out for `TVector3`, the `TVector2` interface would be the same, so I can pil that into the same PR.
