### ISSUE TITLE
Recursion error with *=

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot-methods#28]
If you use `*`, the following works:

```python
a = TVector3Array([1,2], [2,3], [3,4])
b = np.array([2,3])
a = a * b
```

But, with `*=`, an odd error occurs:

```python
a *= b
```

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-71-0d04f348f081> in <module>()
----> 1 a *= b

~/anaconda3/lib/python3.7/site-packages/numpy/lib/mixins.py in func(self, other)
     41     """Implement an in-place binary method with a ufunc, e.g., __iadd__."""
     42     def func(self, other):
---> 43         return ufunc(self, other, out=(self,))
     44     func.__name__ = '__i{}__'.format(name)
     45     return func

~/anaconda3/lib/python3.7/site-packages/uproot_methods/classes/TVector3.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    187 
    188         else:
--> 189             return super(ArrayMethods, self).__array_ufunc__(ufunc, method, *inputs, **kwargs)
    190 
    191 class Methods(Common, uproot_methods.common.TVector.Methods, uproot_methods.base.ROOTMethods):

~/anaconda3/lib/python3.7/site-packages/awkward/array/objects.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    216                 contents.append(x)
    217 
--> 218         result = getattr(ufunc, method)(*contents, **kwargs)
    219 
    220         if awkward.util.iscomparison(ufunc):

~/anaconda3/lib/python3.7/site-packages/awkward/array/table.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    623         tuplelen = None
    624         for n, x in inputsdict.items():
--> 625             newcolumns[n] = getattr(ufunc, method)(*x, **kwargs)
    626 
    627             if tuplelen is None:

~/anaconda3/lib/python3.7/site-packages/uproot_methods/classes/TVector3.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    187 
    188         else:
--> 189             return super(ArrayMethods, self).__array_ufunc__(ufunc, method, *inputs, **kwargs)
    190 
    191 class Methods(Common, uproot_methods.common.TVector.Methods, uproot_methods.base.ROOTMethods):

~/anaconda3/lib/python3.7/site-packages/awkward/array/objects.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    216                 contents.append(x)
    217 
--> 218         result = getattr(ufunc, method)(*contents, **kwargs)
    219 
    220         if awkward.util.iscomparison(ufunc):

... last 2 frames repeated, from the frame below ...

~/anaconda3/lib/python3.7/site-packages/uproot_methods/classes/TVector3.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    187 
    188         else:
--> 189             return super(ArrayMethods, self).__array_ufunc__(ufunc, method, *inputs, **kwargs)
    190 
    191 class Methods(Common, uproot_methods.common.TVector.Methods, uproot_methods.base.ROOTMethods):

RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by jpivarski** [comment]
I put this into PR #29 as well: a `NotImplementedError` when in-place operations are used. Doing this properly will take some thought. I could make `a *= x` be a synonym for `a[:] = a * x`, but that defeats the purpose of why someone would want to do an in-place operation, generally for speed or minimizing the memory footprint. The intermediate steps in computing some of these in-place operations (particularly the jagged ones) are not conservative.

For awkward-arrays, in-place operations should be permanently forbidden because they lead to subtle and likely confusing effects in general. For instance, a jagged array that references its own subarrays more than once is allowed, and you can get into that state by doing fancy indexing on the jagged array (because it applies that operation on the `starts` and `stops` arrays, not the `content`). Then changing an item in subarray 100 in-place could change an item in subarray 120, which would be very confusing. The awkward-array repo has an [OLD-has-setitem-methods](https://github.com/scikit-hep/awkward-array/tree/OLD-has-setitem-methods) with the last implementation of `__setitem__` methods, when I gave up on awkward-arrays having mutable content (in addition to mutable metadata), and now it's hopelessly out of date (but provides an example of how these methods could be reimplemented, if we ever revisit this idea).

We can be more aggressive with in-place operations on arrays of `T*Vector*s`, though. They have a much simpler structure and— as long as they're not inside a jagged array or other awkward class— should be mutable without gotchas. I just haven't thought through how that should be implemented (to the extent that I didn't notice that `NDArrayOperatorsMixin` is calling ufuncs with an `out` parameter). It was also a surprise to learn that if an array is in the `out` parameter, it's _also_ included in `inputs`, which is what I transform, which led to the infinite recursion because `out=self`.

Something as simple as `*=` should be easy, but we'll have to think about boundaries: the `__array_ufunc__` is implemented in general: are there any ufuncs we need to forbid or are they all easy?

**Comment by jpivarski** [comment]
This is going into version 0.3.2 (PR #29 has been merged).
