### ISSUE TITLE
issue with the Numpy() method for TH2

### ISSUE THREAD

**Issue by alasfar-lina** [scikit-hep/uproot-methods#36]
I have seen that someone commented that in TH1  values and allvalues methods were mixed somehow and this is fixed.. However, there is still an issue with TH2 when calling the Numpy() method on them.. I get : 

  File "data_MC_plots.py", line 18, in <module>
    arr, bins= histo_pythia.numpy()
ValueError: too many values to unpack (expected 2)

I have an older uproot version for my python 2 installation and this implementation  used to work.. now for some reason it does not !

**Comment by alasfar-lina** [comment]
I can get Numpy()  to work  by defining only one variable but then the histogram entries and bin edges would be in a single array that I need to take slices of, which I find  harder to use ...

**Comment by jpivarski** [comment]
Now it's

```python
arr, xbins, ybins = histo_pythia.numpy()
```

The discussion was about making the output of this method agree with the format of Numpy's `numpy.histogram2d`. (It used to be different from Numpy, now it's the same.) You can also find this out by printing the output of this method and seeing its structure.

Also, you shouldn't have to use an old uproot for Python 2. uproot still supports Python 2 (at least, Python 2.7— we had to drop Python 2.6 support, but that was before uproot-methods existed, so that's not what you're talking about).

**Comment by jpivarski** [comment]
Our comments crossed in the aether. I don't understand what you're saying about the single array: two-dimensional edges are in two arrays, not one (I just checked the code).

**Comment by jpivarski** [comment]
Oh,I see what you mean— by "one variable," you mean to take it all as a tuple and decompose it with `[0]`, `[1]`, `[2]`, right?

**Comment by alasfar-lina** [comment]
I see, I do not mind it this way.. In fact , it is better as you said..
I tried it and it worked like a charm ... I just did not know about the change 
Regarding my python 2.7 , I just did not upgrade the uproot installation..

Thanks for the quick reply

**Comment by alasfar-lina** [comment]
> Oh,I see what you mean— by "one variable," you mean to take it all as a tuple and decompose it with `[0]`, `[1]`, `[2]`, right?

Yes, exactly

**Comment by jpivarski** [comment]
Okay, glad it's working for you now!

**Comment by alasfar-lina** [comment]
But after you're clarification.. I do not an issue here, at all
