### ISSUE TITLE
New version doesn't allow add columns to JaggedTLorentzVectorArray

### ISSUE THREAD

**Issue by zhenbinwu** [scikit-hep/uproot-methods#44]
The JaggedTLorentzVectorArray is defined as 

`JaggedTLorentzVectorArray = awkward.Methods.mixin(uproot_methods.classes.TLorentzVector.ArrayMethods, awkward.JaggedArray)`

It was later on treated as awkward.Table and adding new columns by
`jaggedarray[att] =arrays[k]`

This used to work fine, but started to break down with the latest update. I got errors as
```
  File "/uscms_data/d3/benwu/temp/CMSSW_10_2_11/src/NanoUpTools/test/../../NanoUpTools/framework/datamodel.py", line 73, in Object
    jaggedarray[att] =arrays[k]
  File "/uscms/home/benwu/.local/lib/python2.7/site-packages/awkward/array/jagged.py", line 756, in __setitem__
    self._content[where] = self.tojagged(what)._content
  File "/uscms/home/benwu/.local/lib/python2.7/site-packages/awkward/array/jagged.py", line 774, in tojagged
    return self.copy(content=data._content[self.IndexedArray.invert((self.index + self._starts)._content)])
  File "/uscms/home/benwu/.local/lib/python2.7/site-packages/numpy/lib/mixins.py", line 25, in func
    return ufunc(self, other)
  File "/uscms/home/benwu/.local/lib/python2.7/site-packages/uproot_methods/classes/TLorentzVector.py", line 301, in __array_ufunc__
    raise TypeError("(arrays of) TLorentzVector can only be added to/subtracted from other (arrays of) TLorentzVector")
TypeError: (arrays of) TLorentzVector can only be added to/subtracted from other (arrays of) TLorentzVector
```

**Comment by jpivarski** [comment]
Okay, I have a recommendation for how to make this array. Constructing arrays with mix-ins is subtle and I don't have a user friendly interface yet. (Having a `Methods` class makes it better than it used to be, though!) But in doing so, I discovered two bugs in last night's release to awkward-array, so these instructions should be used in PR scikit-hep/awkward-array#101. Sorry for the trouble.

Starting with a fake jagged Lorentz vector array,

```python
>>> import awkward, uproot_methods
>>> pt = awkward.fromiter([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
>>> a = uproot_methods.TLorentzVectorArray.from_ptetaphim(pt, pt*2, pt-3, 0.511)
```

Take a look at both its class and its content's class: they _both_ have to be endowed with fancy physics methods. That's the tricky part, which has led to most of the bugs I've fixed.

```python
>>> a.__class__.__bases__
(<class 'uproot_methods.classes.TLorentzVector.PtEtaPhiMassArrayMethods'>, <class 'awkward.array.jagged.JaggedArray'>)
>>> a.content.__class__.__bases__
(<class 'uproot_methods.classes.TLorentzVector.PtEtaPhiMassArrayMethods'>, <class 'awkward.array.objects.ObjectArray'>)
```

Now let's make a class with more fancy methods. This one class needs to have all the array methods within it—yours and the `TLorentzVector.PtEtaPhiMassArrayMethods`—so let's make it a subclass.

```python
>>> class ParticleWithStuff(uproot_methods.classes.TLorentzVector.PtEtaPhiMassArrayMethods):
...     @property
...     def isolation(self):
...         return self["isolation"]
... 
```

This is my recommendation for attribute-style access to physics properties: add them as Python properties, rather than a generic `__getattr__` method. It requires you to know all the names of the properties you'll want, but you do because they come from the TTree and you can add them to the class dynamically:

```python
>>> def newproperty(name):   # have to make the lambda in a function because of Python scoping rules
...     return property(lambda self: self[name])
... 
>>> for name in ["one", "two", "three"]:
...     setattr(ParticleWithStuff, name, newproperty(name))
... 
```

Now getting back to the key point, _both_ the `JaggedArray` and the `ObjectArray` need to be particles with stuff.

```python
>>> ParticleWithStuffJaggedArray = awkward.Methods.mixin(ParticleWithStuff, awkward.JaggedArray)
>>> ParticleWithStuffArray = awkward.Methods.mixin(ParticleWithStuff, awkward.ObjectArray)
>>> a.__class__ = ParticleWithStuffJaggedArray
>>> a.content.__class__ = ParticleWithStuffArray
```

Of course, that property would fail if you don't actually have an `"isolation"` in the `Table`, so let's add it.

```python
>>> a["isolation"] = awkward.fromiter([[0.9, 0, 0.5], [], [0, 0.7]])
```

And now it works, and importantly, it works at all levels:

```python
>>> a.isolation
<JaggedArray [[0.9 0.0 0.5] [] [0.0 0.7]] at 0x7b5936451b70>
>>> a.content.isolation
array([0.9, 0. , 0.5, 0. , 0.7])
```

This is still a Lorentz vector array with all of its methods:

```python
>>> a.mass
<JaggedArray [[0.511 0.511 0.511] [] [0.511 0.511]] at 0x7b5936451b70>
>>> a.content.mass
array([0.511, 0.511, 0.511, 0.511, 0.511])
```

It's important to note that if you use this in a mathematical formula, the result is not a `ParticleWithStuff` but a `TLorentzVector.ArrayMethods`. Like, if you combine two particles to get a candidate, that candidate can't have the isolation of its constituents, right?

```python
>>> b = (a + 2*a)
>>> b.mass
<JaggedArray [[5.448180488809256 28.616731788970416 127.88273017018854] [] [510.2313200892317 1898.5468126964897]] at 0x7b5936451e80>
>>> b.content.mass
array([   5.44818049,   28.61673179,  127.88273017,  510.23132009,
       1898.5468127 ])

>>> # but...
>>> b.isolation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'JaggedArrayMethods' object has no attribute 'isolation'
```

However, slicing or filtering the `ParticleWithStuff` array doesn't make it lose its identity.

```python
>>> c = a[[False, True, True]]
>>> c
<JaggedArrayMethods [[] [TLorentzVector(4.4, 8.8, 1.4, 0.511) TLorentzVector(5.5, 11, 2.5, 0.511)]] at 0x7b5936451e80>
>>> c.isolation
<JaggedArray [[] [0.0 0.7]] at 0x7b5936451c88>
```

Just be sure to pick up that PR. I'm going to add one more bug-fix to it before deploying with a new version number. (Only the `awkward` library.)
