### ISSUE TITLE
uproot-methods v0.5.1 breaking pyhf

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot-methods#53]
Hi @jpivarski, in the pyhf test suite [we're seeing problems](https://travis-ci.org/diana-hep/pyhf/jobs/523523510#L415) caused by [`uproot-methods` release `v0.5.1`](https://github.com/scikit-hep/uproot-methods/releases/tag/0.5.1) (The test-suite passes if I pin `uproot-methods` at `v0.5.0`). The main culprit seems to be

```
E   ModuleNotFoundError: No module named 'uproot.write.objects.TH'
```

I'm taking a look at this now, but I just wanted to bring it to your attention.

**Comment by matthewfeickert** [comment]
Ah, I [now see](https://github.com/scikit-hep/uproot-methods/pull/51#issue-272419450) that this is because [`uproot` PR 269](https://github.com/scikit-hep/uproot/pull/269) hasn't been finished. I'll follow up there.

**Comment by jpivarski** [comment]
You'll probably follow up where @reikdas sees this, but I'll point him to it anyway.

Formally, we should have done another semimajor version (x.y.0) and started a series of release candidates, but I thought that this change only affected new features that aren't public yet. It had escaped my attention that `TH` is an uproot class that doesn't exist yet, rather than a ROOT class (that would come into being through streamers). I see the mistake now.

Thanks for catching this. I think that it could be fixed by including a check for `TH` or `TH1` with a resolution order that doesn't touch the nonexistent class (i.e. only checking for a name string match, which I think the affected code does anyway, to avoid loading a bunch of modules just to check for their types).

**Comment by reikdas** [comment]
I knew this could cause a problem and was hoping to have the uproot pull request merged in along with this but I didn't see me running into that unforeseen error with the tests :(

**Comment by matthewfeickert** [comment]
> I didn't see me running into that unforeseen error with the tests

@reikdas I think we've all been in this situation before. :) I'm sure we'll get it fixed soon enough, so don't worry about it. :+1:

**Comment by matthewfeickert** [comment]
Resolved by [`uproot` PR 269](https://github.com/scikit-hep/uproot/pull/269) and release of `uproot` `v3.5.1`.
